# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 's1.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_server(object):
    def setupUi(self, server):
        server.setObjectName("server")
        server.resize(640, 600)
        self.centralwidget = QtWidgets.QWidget(server)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(30, 10, 261, 16))
        self.label.setObjectName("label")
        self.radioButton = QtWidgets.QRadioButton(self.centralwidget)
        self.radioButton.setGeometry(QtCore.QRect(30, 50, 82, 17))
        self.radioButton.setObjectName("radioButton")
        self.radioButton_2 = QtWidgets.QRadioButton(self.centralwidget)
        self.radioButton_2.setEnabled(True)
        self.radioButton_2.setGeometry(QtCore.QRect(30, 30, 82, 17))
        self.radioButton_2.setAutoFillBackground(False)
        self.radioButton_2.setChecked(True)
        self.radioButton_2.setObjectName("radioButton_2")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(400, 20, 191, 21))
        self.pushButton.setObjectName("pushButton")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(0, 100, 640, 480))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(False)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(50)
        font.setStrikeOut(False)
        self.label_2.setFont(font)
        self.label_2.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_2.setText("")
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        server.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(server)
        self.statusbar.setObjectName("statusbar")
        server.setStatusBar(self.statusbar)

        self.retranslateUi(server)
        QtCore.QMetaObject.connectSlotsByName(server)

    def retranslateUi(self, server):
        _translate = QtCore.QCoreApplication.translate
        server.setWindowTitle(_translate("server", "MainWindow"))
        self.label.setText(_translate("server", "Р Р°Р·СЂРµС€РёС‚СЊ РїРѕРґРєР»СЋС‡РµРЅРёРµ РґР»СЏ "))
        self.radioButton.setText(_translate("server", "all"))
        self.radioButton_2.setText(_translate("server", "localhost"))
        self.pushButton.setText(_translate("server", "РџРѕСЃС‚СЂРѕРёС‚СЊ РіСЂР°С„РёРє"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    server = QtWidgets.QMainWindow()
    ui = Ui_server()
    ui.setupUi(server)
    server.show()
    sys.exit(app.exec_())